/// This is auto generated file
/// Do not modify this file manually

import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {},
        "bn": {},
        "de": {
          "home": "Startseite",
          "songs": "Songs",
          "playlists": "Wiedergabelisten",
          "albums": "Alben",
          "settings": "Einstellungen",
          "libSongs": "Songs aus der Bibliothek",
          "libPlaylists": "Wiedergabelisten aus der Bibliothek",
          "libAlbums": "Alben aus der Bibliothek",
          "libArtists": "Künstler/innen aus der Bibliothek",
          "items": "Artikel",
          "networkError1": "Ups, Netzwerkfehler!",
          "retry": "Wiederholen!",
          "noOfflineSong": "Keine Offline-Lieder!",
          "favorites": "Favoriten",
          "cachedOrOffline": "Zwischengespeichert/Oflline",
          "emptyPlaylist": "Leere Wiedergabeliste!",
          "enqueueAll": "Alle in die Warteschlange einreihen",
          "renamePlaylist": "Wiedergabeliste umbenennen",
          "removePlaylist": "Wiedergabeliste entfernen",
          "CreateNewPlaylist": "Neue Wiedergabeliste erstellen",
          "cancel": "Abbrechen",
          "create": "Erstellen",
          "createnAdd": "Erstellen & hinzufügen",
          "noBookmarks": "Keine Lesezeichen!",
          "startRadio": "Radio starten",
          "enqueueSong": "Dieses Lied einreihen",
          "goToAlbum": "Zum Album",
          "viewArtist": "Künstler/innen ansehen",
          "shareSong": "Dieses Lied teilen",
          "removeFromQueue": "Aus der Warteschlange entfernen",
          "removeFromCache": "Aus dem Zwischenspeicher entfernen",
          "dynamic": "Dynamisch",
          "themeMode": "Themenmodus",
          "quickPics": "Schnellauswahl",
          "discover": "Entdecke",
          "systemDefault": "Systemvorgabe",
          "dark": "dunkel",
          "light": "hell",
          "trending": "Trend",
          "topMusicVid": "Top-Musikvideos",
          "skipSilence": "Stille überspringen",
          "basedOnLast": "Basierend auf der letzten Interaktion",
          "cacheSongs": "Cache-Songs",
          "cacheSongsDes":
              "Das Zwischenspeichern von Titeln während der Wiedergabe für die zukünftige/offline-Wiedergabe, nimmt zusätzlichen Speicherplatz auf Ihrem Gerät in Anspruch.",
          "streamingQuality": "Qualität des Streamings",
          "streamingQualityDes": "Qualität des Musikstreams",
          "high": "hoch",
          "low": "niedrig",
          "equalizer": "Equalizer",
          "equalizerDes": "Öffnet den System-Equalizer",
          "ignoreBatOpt": "Akku-Optimierung ignorieren",
          "status": "Status",
          "enabled": "Aktiviert",
          "disabled": "Deaktiviert",
          "ignoreBatOptDes":
              "Wenn Sie Probleme mit Benachrichtigungen haben oder die Wiedergabe durch die Systemoptimierung gestoppt wird, aktivieren Sie bitte diese Option",
          "github": "Github",
          "githubDes":
              "Github-Quellcode ansehen\nWenn Ihnen dieses Projekt gefällt, vergessen Sie nicht, es zu bewerten ⭐",
          "by": "Unter",
          "videos": "Video",
          "search": "Suche",
          "searchDes": "Lieder, Wiedergabeliste, Album oder Künstler/innen",
          "searchRes": "Suchergebnisse",
          "for1": "für",
          "viewAll": "Alle anzeigen",
          "about": "Über",
          "radioNotAvailable": "Radio für diesen Künstler/in nicht verfügbar!",
          "songRemovedfromQueue": "Aus der Warteschlange entfernt!",
          "songRemovedfromQueueCurrSong":
              "Sie können den aktuell gespielten Titel nicht entfernen",
          "songAddedToPlaylistAlert": "Song zur Wiedergabeliste hinzugefügt!",
          "songAlreadyExists": "Das Lied existiert bereits!",
          "songEnqueueAlert": "Lied in der Warteschlange!",
          "songRemovedAlert": "Entfernt von",
          "errorOccuredAlert": "Es ist ein Fehler aufgetreten!",
          "playlistCreatednsongAddedAlert":
              "Wiedergabeliste erstellt & Lied hinzugefügt!",
          "playlistRenameAlert": "Erfolgreich umbenannt!",
          "playlistRemovedAlert": "Wiedergabeliste entfernt!",
          "playlistBookmarkAddAlert":
              "Wiedergabeliste als Lesezeichen markiert!",
          "playlistBookmarkRemoveAlert":
              "Wiedergabeliste-Lesezeichen entfernt!",
          "selectAuthIns": "Autorisierungsinstanz auswählen",
          "reset": "Zurücksetzen",
          "artists": "Künstler/innen",
          "recentlyPlayed": "Kürzlich abgespielt",
          "playNext": "Als nächstes Wiedergeben",
          "addToPlaylist": "Zur Wiedergabeliste hinzufügen",
          "noLibPlaylist": "Du hast keine Playlist in der Bibliothek!",
          "skipSilenceDes": "Stille wird bei der Musikwiedergabe übersprungen",
          "results": "Ergebnisse",
          "nomatch": "Keine Übereinstimmung gefunden für",
          "subscribers": "Abonnenten",
          "playlistCreatedAlert": "Playlist erstellt!",
          "albumBookmarkAddAlert": "Album als Lesezeichen markiert!",
          "albumBookmarkRemoveAlert": "Album-Lesezeichen entfernt!",
          "artistDesNotAvailable": "Beschreibung nicht verfügbar!",
          "dontShowInfoAgain": "Diese Information nicht mehr anzeigen",
          "artistBookmarkAddAlert": "Künstler/in als Lesezeichen markiert!",
          "artistBookmarkRemoveAlert": "Künstler-Lesezeichen entfernt!",
          "newVersionAvailable": "Neue Version verfügbar!",
          "lyricsNotAvailable": "Liedtext nicht verfügbar!",
          "dismiss": "Ablehnen",
          "notaSongVideo": "Kein Lied/Musik-Video!",
          "unLink": "Aufheben der Verknüpfung",
          "notaValidLink": "Kein gültiger Link!",
          "link": "Verknüpfung",
          "operationFailed": "Operation fehlgeschlagen",
          "local": "Lokal",
          "goToDownloadPage":
              "Klicken Sie hier, um zur Download-Seite zu gelangen",
          "linkPipedDes": "Mit Piped verknüpfen",
          "username": "Benutzername",
          "password": "Passwort",
          "linkAlert": "Erfolgreich verbunden!",
          "unlinkAlert": "Verknüpfung erfolgreich getrennt!",
          "playlistBlacklistAlert":
              "Wiedeegabeliste auf die schwarze Liste gesetzt!",
          "blacklistPlstResetAlert": "Erfolgreich zurückgesetzt!",
          "resetblacklistedplaylistDes":
              "Setzen Sie alle Piped Wiedergabelisten auf der schwarzen Liste zurück",
          "resetblacklistedplaylist":
              "Auf die schwarze Liste gesetzte Wiedergabelisten zurücksetzen",
          "setDiscoverContent": "Entdecken Sie Inhalte",
          "stopMusicOnTaskClear":
              "Musik stoppen wenn die Taskleiste geleert wird",
          "stopMusicOnTaskClearDes":
              "Die Musikwiedergabe wird gestoppt, wenn die App aus dem Task-Manager weggewischt wird"
        },
        "en": {
          "home": "Home",
          "songs": "Songs",
          "playlists": "Playlists",
          "albums": "Albums",
          "singles": "Singles",
          "artists": "Artists",
          "settings": "Settings",
          "libSongs": "Library Songs",
          "libPlaylists": "Library Playlists",
          "libAlbums": "Library Albums",
          "libArtists": "Library Artists",
          "communityplaylists": "Community Playlists",
          "featuredplaylists": "Featured Playlists",
          "items": "items",
          "networkError1": "Oops network error!",
          "retry": "Retry!",
          "noOfflineSong": "No offline songs!",
          "recentlyPlayed": "Recently Played",
          "favorites": "Favorites",
          "cachedOrOffline": "Cached/Offline",
          "emptyPlaylist": "Empty playlist!",
          "enqueueAll": "Enqueue all",
          "renamePlaylist": "Rename Playlist",
          "removePlaylist": "Remove playlist",
          "CreateNewPlaylist": "Create new playlist",
          "cancel": "Cancel",
          "create": "Create",
          "rename": "Rename",
          "createnAdd": "Create & add",
          "noBookmarks": "No bookmarks!",
          "startRadio": "Start radio",
          "playNext": "Play next",
          "addToPlaylist": "Add to playlist",
          "noLibPlaylist": "You don't have any lib playlist!",
          "enqueueSong": "Enqueue this song",
          "goToAlbum": "Go to album",
          "viewArtist": "View Artist",
          "shareSong": "Share this song",
          "removeFromPlaylist": "Remove from playlist",
          "removeFromQueue": "Remove from queue",
          "removeFromCache": "Remove from cache",
          "themeMode": "Theme Mode",
          "dynamic": "Dynamic",
          "systemDefault": "System default",
          "dark": "dark",
          "light": "light",
          "language": "Language",
          "languageDes": "Set App language",
          "setDiscoverContent": "Set discover content",
          "quickpicks": "Quick Picks",
          "discover": "Discover",
          "trending": "Trending",
          "topmusicvideos": "Top Music Videos",
          "basedOnLast": "Based on last interaction",
          "cacheSongs": "Cache Songs",
          "cacheSongsDes":
              "Caching songs while playing for future/offline playback, it will take additional space on your device",
          "skipSilence": "Skip silence",
          "skipSilenceDes": "Silence will be skipped in music playback",
          "streamingQuality": "Streaming quality",
          "streamingQualityDes": "Quality of music stream",
          "high": "High",
          "low": "Low",
          "equalizer": "Equalizer",
          "equalizerDes": "open system equalizer",
          "ignoreBatOpt": "Ignore battery optimization",
          "ignoreBatOptDes":
              "If you are facing notification issues or playback stopped by system optimization, please enable this option",
          "status": "Status",
          "enabled": "Enabled",
          "disabled": "Disabled",
          "github": "GitHub",
          "githubDes":
              "View GitHub source code \nif you like this project, don't forget to give a ⭐",
          "by": "by",
          "search": "Search",
          "searchDes": "Songs,Playlist,Album or Artist",
          "searchRes": "Search results",
          "for1": "for",
          "videos": "Videos",
          "viewAll": "View all",
          "results": "Results",
          "nomatch": "No Match found for",
          "subscribers": "subscribers",
          "about": "About",
          "radioNotAvailable": "Radio not available for this artist!",
          "songRemovedfromQueue": "Removed from queue!",
          "songRemovedfromQueueCurrSong":
              "You can't remove currently playing song",
          "songAddedToPlaylistAlert": "Song added to playlist!",
          "songAlreadyExists": "Song already exists!",
          "songEnqueueAlert": "Song enqueued!",
          "songRemovedAlert": "Removed from",
          "errorOccuredAlert": "Some error occured!",
          "playlistCreatedAlert": "Playlist created!",
          "playlistCreatednsongAddedAlert": "Playlist created & song added!",
          "playlistRenameAlert": "Renamed successfully!",
          "playlistRemovedAlert": "Playlist removed!",
          "playlistBookmarkAddAlert": "Playlist bookmarked!",
          "playlistBookmarkRemoveAlert": "Playlist bookmark removed!",
          "albumBookmarkAddAlert": "Album bookmarked!",
          "albumBookmarkRemoveAlert": "Album bookmark removed!",
          "artistBookmarkAddAlert": "Artist bookmarked!",
          "artistBookmarkRemoveAlert": "Artist bookmark removed!",
          "lyricsNotAvailable": "Lyrics not available!",
          "artistDesNotAvailable": "Description not available!",
          "newVersionAvailable": "New version available!",
          "dontShowInfoAgain": "Don't show this info again",
          "dismiss": "Dismiss",
          "notaSongVideo": "Not a Song/Music-Video!",
          "notaValidLink": "Not a valid link!",
          "operationFailed": "Operation failed",
          "goToDownloadPage": "Click here to go to download page",
          "local": "Local",
          "Piped": "Piped",
          "link": "Link",
          "unLink": "Unlink",
          "hintApiUrl": "Piped instance api url",
          "customIns": "Custom Instance",
          "customInsSelectMsg": "Please select Custom Instance",
          "selectAuthInsMsg": "Please select Authentication instance!",
          "allFieldsReqMsg": "All fields required",
          "linkPipedDes": "Link with piped for playlists",
          "selectAuthIns": "Select Auth Instance",
          "username": "Username",
          "password": "Password",
          "linkAlert": "Linked successfully!",
          "unlinkAlert": "Unlinked successfully!",
          "playlistBlacklistAlert": "Playlist blacklisted!",
          "reset": "Reset",
          "blacklistPlstResetAlert": "Reset successfully!",
          "resetblacklistedplaylist": "Reset blacklisted playlists",
          "resetblacklistedplaylistDes":
              "Reset all the piped blacklisted playlists",
          "stopMusicOnTaskClear": "Stop music on task clear",
          "stopMusicOnTaskClearDes":
              "Music playback will stop when App being swiped away from the task manager"
        },
        "es": {
          "playlistCreatednsongAddedAlert":
              "¡Lista de reproducción creada y la canción fue añadida!",
          "dismiss": "Descartar",
          "goToDownloadPage":
              "Haz clic aquí para ir a la página de las descargas",
          "songEnqueueAlert": "¡Canción en la cola!",
          "renamePlaylist": "Renombrar la lista de reproducción",
          "songAddedToPlaylistAlert": "¡Canción añadida a la lista!",
          "unlinkAlert": "¡Desvinculado con éxito!",
          "playlistCreatedAlert": "¡Lista de reproducción creada!",
          "reset": "Restablecer",
          "unLink": "Desvincular",
          "trending": "Tendencias",
          "searchRes": "Resultados de la búsqueda",
          "cacheSongsDes":
              "Almacenamiento de las canciones en la caché durante la reproducción para futuras reproducciones sin conexión, lo que ocupará espacio adicional en el dispositivo",
          "password": "Contraseña",
          "noLibPlaylist": "¡No tienes ninguna lista de reproducción lib!",
          "setDiscoverContent": "Como se detecta el contenido",
          "networkError1": "¡Vaya, un error en la conexión!",
          "songRemovedfromQueue": "¡Eliminado de la cola!",
          "libSongs": "Canciones de la biblioteca",
          "githubDes":
              "Ver el código fuente en GitHub \nsi te gusta este proyecto, no te olvides de dar una ⭐",
          "communityplaylists": "Listas de reproducción públicas",
          "playlistRemovedAlert": "¡Lista eliminada!",
          "libAlbums": "Álbumes de la biblioteca",
          "albumBookmarkRemoveAlert": "¡Marcador del álbum eliminado!",
          "notaSongVideo": "¡No es una canción/vídeo musical!",
          "ignoreBatOptDes":
              "Si tienes problemas con las notificaciones o la reproducción se detiene por la optimización del sistema, por favor activa esta opción",
          "for1": "para",
          "low": "Baja",
          "link": "Enlace",
          "selectAuthIns": "Selecciona una Instancia Authance",
          "languageDes": "Idioma de la aplicación",
          "stopMusicOnTaskClear":
              "Detener la música cuando se limpia la barra de tareas",
          "enqueueAll": "Poner todo en la cola",
          "customInsSelectMsg":
              "Por favor, selecciona una Instancia personalizada",
          "skipSilence": "Omitir el silencio",
          "create": "Crear",
          "equalizer": "Ecualizador",
          "enqueueSong": "Poner en la cola esta canción",
          "noBookmarks": "¡Sin marcadores!",
          "playlists": "Listas de reproducción",
          "videos": "Vídeos",
          "enabled": "Activado",
          "allFieldsReqMsg": "Todos los campos son obligatorios",
          "artistBookmarkAddAlert": "¡Artista marcado como favorito!",
          "removeFromCache": "Eliminar de la caché",
          "rename": "Cambie el nombre",
          "viewAll": "Ver todo",
          "github": "GitHub",
          "newVersionAvailable": "¡Nueva versión disponible!",
          "items": "elementos",
          "subscribers": "suscriptores",
          "startRadio": "Iniciar la radio",
          "discover": "Descubrir",
          "cacheSongs": "Canciones en caché",
          "songAlreadyExists": "¡La canción ya existe!",
          "libArtists": "Artistas de la biblioteca",
          "username": "Nombre de usuario",
          "light": "Claro",
          "resetblacklistedplaylist": "Restablecer las listas negras",
          "dynamic": "Dinámico",
          "selectAuthInsMsg":
              "¡Por favor, selecciona la instancia de la autenticación!",
          "equalizerDes": "Abrir el ecualizador del sistema",
          "removePlaylist": "Eliminar la lista de reproducción",
          "customIns": "Instancia personalizada",
          "Piped": "Piped",
          "addToPlaylist": "Añadir a la lista de reproducción",
          "stopMusicOnTaskClearDes":
              "La reproducción de la música se detendrá cuando se desplace la aplicación fuera de la barra de tareas",
          "cachedOrOffline": "En caché/sin conexión",
          "retry": "¡Volver a intentarlo!",
          "artists": "Artistas",
          "playlistBookmarkAddAlert": "¡Lista de reproducción favorita!",
          "albums": "Álbumes",
          "radioNotAvailable": "¡Radio no disponible para este artista!",
          "recentlyPlayed": "Reproducido recientemente",
          "viewArtist": "Ver el artista",
          "createnAdd": "Crear y añadir",
          "topmusicvideos": "Vídeos musicales más vistos",
          "about": "Acerca de",
          "playlistBookmarkRemoveAlert":
              "¡Marcador de lista de reproducción eliminado!",
          "systemDefault": "Predeterminado del sistema",
          "local": "Local",
          "ignoreBatOpt": "Ignorar la optimización de la batería",
          "singles": "Sencillos",
          "linkAlert": "¡Vinculado con éxito!",
          "status": "Estado",
          "themeMode": "Modo del tema",
          "streamingQualityDes": "Calidad de la música",
          "nomatch": "No se han encontrado coincidencias para",
          "notaValidLink": "¡No es un enlace válido!",
          "emptyPlaylist": "¡Lista de reproducción vacía!",
          "favorites": "Favoritos",
          "dark": "Oscuro",
          "home": "Inicio",
          "cancel": "Cancelar",
          "by": "por",
          "streamingQuality": "Calidad del streaming",
          "linkPipedDes": "Enlace con las listas de reproducción",
          "libPlaylists": "Listas de reproducción de la biblioteca",
          "disabled": "Desactivado",
          "CreateNewPlaylist": "Crear una nueva lista de reproducción",
          "blacklistPlstResetAlert": "¡Reiniciado con éxito!",
          "language": "Idioma",
          "search": "Buscar",
          "skipSilenceDes":
              "El silencio se omitirá en la reproducción de la música",
          "playNext": "Siguiente",
          "errorOccuredAlert": "¡Ha ocurrido un error!",
          "songs": "Canciones",
          "high": "Alta",
          "searchDes": "Canciones,Lista de reproducción,Álbum o Artista",
          "results": "Resultados",
          "playlistBlacklistAlert": "¡Lista de reproducción en la lista negra!",
          "artistDesNotAvailable": "¡Descripción no disponible!",
          "songRemovedfromQueueCurrSong":
              "No puedes eliminar la canción que se está reproduciendo",
          "settings": "Ahustes",
          "basedOnLast": "Según la última interacción",
          "hintApiUrl": "Dirección url a la api de la instancia de Piped",
          "playlistRenameAlert": "¡Renombrado con éxito!",
          "albumBookmarkAddAlert": "¡Álbum en favoritos!",
          "removeFromPlaylist": "Eliminar de la lista de reproducción",
          "lyricsNotAvailable": "¡Letra no disponible!",
          "dontShowInfoAgain": "No volver a mostrar esta información",
          "noOfflineSong": "¡No hay canciones sin conexión!",
          "featuredplaylists": "Listas de reproducción destacadas",
          "quickpicks": "Selecciones rápidas",
          "artistBookmarkRemoveAlert": "¡Se eliminó el marcador del artista!",
          "operationFailed": "Error en la operación",
          "goToAlbum": "Ir al álbum",
          "removeFromQueue": "Eliminar de la cola",
          "shareSong": "Compartir esta canción",
          "songRemovedAlert": "Eliminado de"
        },
        "fil": {},
        "fj": {},
        "fr": {
          "libPlaylists": "Listes de lecture de bibliothèque",
          "networkError1": "Oups erreur réseau !",
          "noOfflineSong": "Pas de chansons hors ligne !",
          "favorites": "Favoris",
          "cachedOrOffline": "En cache/Hors ligne",
          "emptyPlaylist": "Liste de lecture vide !",
          "enqueueAll": "Mettre tout dans la file",
          "renamePlaylist": "Renommer la liste de lecture",
          "removePlaylist": "Retirer la liste de lecture",
          "CreateNewPlaylist": "Créer une nouvelle liste de lecture",
          "cancel": "Annuler",
          "create": "Créer",
          "createnAdd": "Créer et ajouter",
          "noBookmarks": "Pas de signets !",
          "startRadio": "Démarrer la radio",
          "playNext": "Jouer ensuite",
          "removeFromQueue": "Retirer de la file",
          "removeFromCache": "Retirer du cache",
          "themeMode": "Mode du thème",
          "dynamic": "Dynamique",
          "systemDefault": "Système par défaut",
          "dark": "sombre",
          "light": "clair",
          "setDiscoverContent": "Définir le contenu",
          "quickPics": "Sélection rapide",
          "discover": "Découvrir",
          "trending": "Tendances",
          "topMusicVid": "Palmarès des vidéoclips",
          "basedOnLast": "Basée sur la dernière interaction",
          "cacheSongsDes":
              "Mettre les chansons en cache tout en jouant pour la lecture future/hors ligne, il faudra un espace supplémentaire sur votre appareil",
          "skipSilence": "Ignorer le silence",
          "low": "Basse",
          "equalizer": "Égaliseur",
          "ignoreBatOptDes":
              "Si vous êtes confronté·e à des problèmes de notification ou de lecture arrêtée par l'optimisation du système, veuillez activer cette option",
          "status": "État",
          "enabled": "Activé",
          "disabled": "Désactivé",
          "githubDes":
              "Voir le code source GitHub\nSi vous aimez ce projet, n'oubliez pas de donner une ⭐",
          "search": "Recherche",
          "searchRes": "Résultats de la recherche",
          "videos": "Vidéos",
          "viewAll": "Voir tous",
          "results": "Résultats",
          "nomatch": "Aucune correspondance trouvée pour",
          "subscribers": "abonnés",
          "radioNotAvailable": "Radio non disponible pour cet artiste !",
          "songRemovedfromQueue": "Enlevé de la file !",
          "songRemovedfromQueueCurrSong":
              "Vous ne pouvez pas supprimer jouer actuellement chanson",
          "songAddedToPlaylistAlert": "Chanson ajoutée à la playlist !",
          "songAlreadyExists": "La chanson existe déjà !",
          "songEnqueueAlert": "Chanson en file d'attente !",
          "songRemovedAlert": "Supprimé de",
          "playlistCreatednsongAddedAlert":
              "Liste de lecture créée et chanson ajoutée !",
          "playlistRenameAlert": "Renommé avec succès !",
          "playlistBookmarkRemoveAlert":
              "Signet de la liste de lecture retiré !",
          "albumBookmarkAddAlert": "Album en signet !",
          "albumBookmarkRemoveAlert": "Signet de l'album retiré !",
          "artistBookmarkAddAlert": "Artiste en signet !",
          "artistBookmarkRemoveAlert": "Signet d'artiste enlevé !",
          "dismiss": "Rejeter",
          "operationFailed": "Opération échouée",
          "libSongs": "Chansons de la bibliothèque",
          "home": "Accueil",
          "songs": "Chansons",
          "playlists": "Listes de lecture",
          "albums": "Albums",
          "artists": "Artistes",
          "settings": "Réglages",
          "libAlbums": "Albums de la bibliothèque",
          "retry": "Réessayez !",
          "libArtists": "Artistes de la bibliothèque",
          "items": "éléments",
          "recentlyPlayed": "Joué récemment",
          "addToPlaylist": "Ajouter à la liste de lecture",
          "noLibPlaylist": "Tu n'as pas de lib playlist !",
          "enqueueSong": "Enqueue cette chanson",
          "goToAlbum": "Aller à l'album",
          "viewArtist": "Voir l'artiste",
          "shareSong": "Partager cette chanson",
          "cacheSongs": "Chansons en cache",
          "skipSilenceDes": "Le silence sera ignoré dans la lecture de musique",
          "streamingQuality": "Qualité de diffusion",
          "streamingQualityDes": "Qualité du flux de musique",
          "high": "Élevée",
          "equalizerDes": "ouvrir l'égaliseur du système",
          "ignoreBatOpt": "Ignorer l'optimisation de la batterie",
          "github": "GitHub",
          "by": "par",
          "searchDes": "Chansons,Listes de lecture,Album ou Artiste",
          "for1": "pour",
          "about": "À propos",
          "errorOccuredAlert": "Une erreur s'est produite !",
          "playlistCreatedAlert": "Liste de lecture créée !",
          "playlistRemovedAlert": "Liste de lecture retirée !",
          "playlistBookmarkAddAlert": "Liste de lecture en signet !",
          "lyricsNotAvailable": "Paroles indisponible !",
          "artistDesNotAvailable": "Description indisponible !",
          "newVersionAvailable": "Nouvelle version disponible !",
          "dontShowInfoAgain": "Ne plus afficher cette info",
          "notaSongVideo": "Pas un Song/Music-Video !",
          "notaValidLink": "Pas un lien valable !",
          "local": "Local",
          "link": "Lien",
          "unlinkAlert": "Dissociation réussie !",
          "playlistBlacklistAlert": "Playlist sur liste noire !",
          "reset": "Réinitialiser",
          "blacklistPlstResetAlert": "Réinitialiser avec succès !",
          "resetblacklistedplaylistDes":
              "Réinitialiser toutes les listes de lecture de la liste noire de Piped",
          "goToDownloadPage":
              "Cliquez ici pour accéder à la page de téléchargement",
          "unLink": "séparer",
          "linkPipedDes": "Lien avec piped pour les playlists",
          "selectAuthIns": "Sélectionnez Auth Instance",
          "username": "Nom d'utilisateur",
          "password": "Mot de passe",
          "linkAlert": "Liée avec succès !",
          "resetblacklistedplaylist":
              "Réinitialiser les platlistes sur liste noire",
          "stopMusicOnTaskClearDes":
              "La lecture de musique s'arrêtera quand App sera écarté du gestionnaire de tâches",
          "stopMusicOnTaskClear": "arrêter la musique",
          "communityplaylists": "Playlist de la communauté",
          "languageDes": "définir la langue de l'application",
          "customInsSelectMsg": "Veuillez sélectionner Custom Instance",
          "allFieldsReqMsg": "Tous les champs sont obligatoires",
          "rename": "Renommer",
          "selectAuthInsMsg":
              "Veuillez sélectionner l'instance Authentication !",
          "customIns": "Instance personnalisée",
          "Piped": "Piped",
          "topmusicvideos": "Top Vidéos de musique",
          "singles": "Singles",
          "language": "Langue",
          "hintApiUrl": "URL de l'API de l'instance",
          "removeFromPlaylist": "Retirer de la playlist",
          "featuredplaylists": "Playlist mise en avant",
          "quickpicks": "Sélections rapides"
        },
        "ga": {},
        "hi": {
          "themeMode": "थीम मोड",
          "playlists": "प्लेलिस्ट",
          "albums": "एल्बम",
          "libSongs": "लाइब्रेरी गाने",
          "libAlbums": "लाइब्रेरी एल्बम",
          "items": "आइटम",
          "cachedOrOffline": "ऑफलाइन",
          "renamePlaylist": "प्लेलिस्ट का नाम बदलें",
          "create": "बनाएं",
          "createnAdd": "बनाएँ और जोड़ें",
          "dynamic": "डाइनैमिक",
          "systemDefault": "सिस्टम डिफ़ॉल्ट",
          "dark": "डार्क",
          "home": "होम",
          "songs": "गाने",
          "artists": "कलाकार",
          "settings": "सेटिंग्स",
          "light": "लाइट",
          "retry": "पुन: प्रयास करें!",
          "libArtists": "लाइब्रेरी कलाकार",
          "noOfflineSong": "कोई ऑफ़लाइन गीत नहीं!",
          "networkError1": "उफ़ नेटवर्क त्रुटि!",
          "favorites": "पसंदीदा",
          "recentlyPlayed": "हाल ही में बजाया",
          "emptyPlaylist": "खाली प्लेलिस्ट!",
          "enqueueAll": "सभी कतारबद्ध करें",
          "removePlaylist": "प्लेलिस्ट हटाएँ",
          "noBookmarks": "कोई बुकमार्क नहीं!",
          "CreateNewPlaylist": "नई प्लेलिस्ट बनाएँ",
          "cancel": "रद्द करें",
          "playNext": "अगला चलाएँ",
          "startRadio": "स्टार्ट रेडियो",
          "noLibPlaylist": "आपके पास कोई लाइब्रेरी प्लेलिस्ट नहीं है!",
          "enqueueSong": "कतार में शामिल करें",
          "goToAlbum": "एल्बम पर जाएं",
          "shareSong": "इस गाने को साझा करें",
          "viewArtist": "कलाकार देखें",
          "removeFromQueue": "कतार से निकालें",
          "removeFromCache": "कैश से निकालें",
          "addToPlaylist": "प्लेलिस्ट में जोड़ें",
          "libPlaylists": "लाइब्रेरी प्लेलिस्ट",
          "cacheSongsDes":
              "भविष्य / ऑफ़लाइन प्लेबैक के लिए बजाते समय गाने को कैश करें, यह आपके डिवाइस पर अतिरिक्त स्थान लेगा",
          "skipSilence": "स्किप साइलेंस",
          "skipSilenceDes": "साइलेंस को संगीत प्लेबैक से हटा दिया जाएगा",
          "streamingQuality": "स्ट्रीमिंग गुणवत्ता",
          "streamingQualityDes": "संगीत स्ट्रीम की गुणवत्ता",
          "high": "उच्च",
          "equalizer": "इक्वलाइज़र",
          "low": "कम",
          "equalizerDes": "सिस्टम इक्वलाइज़र को खोले",
          "githubDes":
              "GitHub स्रोत कोड देखें\nयदि आप इस प्रोजेक्ट को पसंद करते हैं, तो एक ⭐देने के लिए मत भूलना",
          "by": "द्वारा",
          "viewAll": "सभी देखें",
          "enabled": "सक्रिय",
          "status": "स्थिति",
          "ignoreBatOptDes":
              "यदि आप नोटिफिकेशन संगीत कण्ट्रोल से सम्बंधित कोई दिक्क्तों का सामना कर रहे है या आपका संगीत प्लेबैक को सिस्टम ऑप्टिमाइजेशन के द्वारा रोक दिया जा रहा तो आप इस ऑप्शन को चालू करे",
          "ignoreBatOpt": "बैटरी ऑप्टिमाइजेशन को इग्नोर करे",
          "disabled": "निष्क्रिय",
          "github": "GitHub",
          "searchRes": "खोज परिणाम",
          "for1": "के लिए",
          "topMusicVid": "शीर्ष संगीत वीडियो",
          "cacheSongs": "कैश गाने",
          "operationFailed": "ऑपरेशन विफल",
          "searchDes": "गाने,प्लेलिस्ट्स ,एलबम्स और कलाकार",
          "results": "परिणाम",
          "search": "खोजें",
          "videos": "वीडियोस",
          "about": "बारे में",
          "radioNotAvailable": "रेडियो इस कलाकार के लिए उपलब्ध नहीं है!",
          "playlistRemovedAlert": "प्लेलिस्ट हट गया!",
          "playlistCreatedAlert": "प्लेलिस्ट बनाया!",
          "playlistBookmarkAddAlert": "प्लेलिस्ट बुकमार्क हो गया!",
          "artistBookmarkAddAlert": "कलाकार बुकमार्क हो गया!",
          "setDiscoverContent": "डिस्कवर कंटेंट सेट करें",
          "quickPics": "गानों का सुझाव",
          "discover": "डिस्कवर",
          "trending": "रुझान में चल रहे गाने",
          "basedOnLast": "अंतिम गतिविधि के आधार पर",
          "subscribers": "सब्सक्राइबर्स",
          "songRemovedfromQueue": "कतार से हटा दिया!",
          "songRemovedfromQueueCurrSong":
              "आप वर्तमान में चल रहे गाने को नहीं हटा सकते",
          "songAddedToPlaylistAlert": "गीत प्लेलिस्ट में जुड़ गया!",
          "songAlreadyExists": "गीत पहले से ही मौजूद है!",
          "songEnqueueAlert": "गाना कतार में जुड़ा !",
          "songRemovedAlert": "से हटाया",
          "errorOccuredAlert": "कुछ त्रुटि हुई!",
          "playlistCreatednsongAddedAlert": "प्लेलिस्ट बनाया और गीत जोड़ा!",
          "playlistRenameAlert": "सफलतापूर्वक बदला गया!",
          "playlistBookmarkRemoveAlert": "प्लेलिस्ट बुकमार्क हट गया!",
          "albumBookmarkAddAlert": "एल्बम बुकमार्क हो गया!",
          "albumBookmarkRemoveAlert": "एल्बम बुकमार्क हट गया!",
          "artistBookmarkRemoveAlert": "कलाकार बुकमार्क हट गया!",
          "lyricsNotAvailable": "Lyrics उपलब्ध नहीं!",
          "artistDesNotAvailable": "विवरण उपलब्ध नहीं!",
          "newVersionAvailable": "नया संस्करण उपलब्ध!",
          "dontShowInfoAgain": "इस जानकारी को फिर से न दिखाएं",
          "dismiss": "बंद करें",
          "notaValidLink": "एक वैध लिंक नहीं!",
          "notaSongVideo": "एक गीत / संगीत वीडियो नहीं!",
          "nomatch": "कोई मैच नहीं मिला",
          "reset": "रिसेट",
          "blacklistPlstResetAlert": "सफलतापूर्वक रिसेट हुआ!",
          "goToDownloadPage": "डाउनलोड पेज पर जाने के लिए यहाँ दबाएं",
          "local": "लोकल",
          "link": "जोड़ें",
          "unLink": "हटाएँ",
          "linkPipedDes": "पाइप्ड के साथ प्लेलिस्ट्स के लिए जोड़ें",
          "username": "यूज़रनेम",
          "password": "पासवर्ड",
          "selectAuthIns": "Auth इंस्टैंस चुने",
          "linkAlert": "सफलतापूर्वक जुड़ गया!",
          "unlinkAlert": "सफलतापूर्वक हट गया!",
          "playlistBlacklistAlert": "प्लेलिस्ट ब्लैकलिस्ट हो गया!",
          "resetblacklistedplaylist": "ब्लैकलिस्टेड प्लेलिस्ट रिसेट",
          "resetblacklistedplaylistDes":
              "सभी पाइप्ड ब्लैकलिस्टेड प्लेलिस्ट्स को रिसेट करें",
          "stopMusicOnTaskClear": "म्यूजिक बंद करें",
          "stopMusicOnTaskClearDes":
              "इस ऐप को टास्क मैनेजर से स्वाइप करने पर म्यूजिक बंद हो जायेगा",
          "communityplaylists": "कम्यूनिटी प्लेलिस्ट",
          "languageDes": "अनुप्रयोग भाषा सेट करें",
          "customInsSelectMsg": "कृपया कस्टम इंस्टेंस का चयन करें",
          "allFieldsReqMsg": "सभी फील्ड भरें",
          "rename": "नाम बदलें",
          "selectAuthInsMsg": "कृपया ऑथेंटिकेशन इंस्टैंस चुने !",
          "customIns": "कस्टम इंस्टेंस",
          "Piped": "पाइप्ड",
          "topmusicvideos": "शीर्ष संगीत वीडियो",
          "singles": "सिंगल्स",
          "language": "भाषा",
          "hintApiUrl": "पाइप्ड इंस्टैंस एपीआई यूआरएल",
          "removeFromPlaylist": "प्लेलिस्ट से निकालें",
          "featuredplaylists": "फीचर्ड प्लेलिस्ट",
          "quickpicks": "गानों का सुझाव"
        },
        "id": {},
        "it": {
          "home": "Pagina principale",
          "songs": "Canzoni",
          "playlists": "Playlist",
          "albums": "Album",
          "artists": "Artisti",
          "settings": "Impostazioni",
          "items": "elementi",
          "networkError1": "Ops errore rete!"
        },
        "ja": {},
        "kn": {"libArtists": "歌手库"},
        "ko": {},
        "ku": {},
        "ml": {},
        "my": {},
        "nb_NO": {
          "home": "Hjem",
          "low": "Lav",
          "high": "Høy",
          "equalizerDes": "åpne system-tonekontroll",
          "newVersionAvailable": "Ny versjon tilgjengelig.",
          "addToPlaylist": "Legg til i spilleliste",
          "viewAll": "Vis alle",
          "subscribers": "abonnenter",
          "enqueueAll": "Legg alt i kø",
          "renamePlaylist": "Gi spillelisten nytt navn",
          "about": "Om",
          "themeMode": "Draktmodus",
          "notaValidLink": "Ugyldig lenke",
          "shareSong": "Del dette sporet",
          "removeFromQueue": "Fjern fra kø",
          "light": "lys",
          "removePlaylist": "Fjern spilleliste",
          "create": "Opprett",
          "skipSilence": "Hopp over stillhet",
          "status": "Status",
          "streamingQualityDes": "Musikkstrømskvalitet",
          "cacheSongsDes": "Under avspilling tar dette ekstra plass på enheten",
          "streamingQuality": "Strømmingskvalitet",
          "ignoreBatOpt": "Ingorer batterioptimalisering",
          "enabled": "På",
          "disabled": "Av",
          "songAlreadyExists": "Sporet finnes allerede",
          "playlistCreatedAlert": "Spilleliste opprettet",
          "playlistRenameAlert": "Navn endret",
          "viewArtist": "Vis artist",
          "dynamic": "Dynamisk",
          "systemDefault": "Systemforvalg",
          "dark": "mørk",
          "createnAdd": "Opprett og legg til",
          "noBookmarks": "Ingen bokmerker",
          "startRadio": "Start radio",
          "playNext": "Spill neste",
          "enqueueSong": "Legg dette sporet i kø",
          "goToAlbum": "Gå til album",
          "removeFromCache": "Fjern fra hurtiglager",
          "basedOnLast": "Basert på siste interaksjon",
          "cacheSongs": "Hurtiglagre spor",
          "noLibPlaylist": "Du har ikke noen biblioteksspilleliste",
          "setDiscoverContent": "Sett oppdagbart innhold",
          "quickPics": "Hurtigbilder",
          "discover": "Oppdagbart",
          "trending": "På vei opp",
          "topMusicVid": "Topp-musikkvideoer",
          "equalizer": "Tonekontroll",
          "github": "GitHub",
          "searchRes": "Søkeresultater",
          "for1": "for",
          "videos": "Videoer",
          "results": "Resultater",
          "by": "av",
          "search": "Søk",
          "skipSilenceDes": "Hopper over tomme deler under musikkavspilling",
          "searchDes": "Spor, spilleliste, album, eller artist",
          "ignoreBatOptDes":
              "Hvis du har merknadsproblemer eller avspilling stoppes av systemoptimalisering",
          "githubDes":
              "Vis kildekoden.\nHvis du liker prosjektet kan du gi en ⭐",
          "songRemovedAlert": "Fjernet fra",
          "dontShowInfoAgain": "Ikke vis denne infoen igjen",
          "nomatch": "Resultatløst for",
          "radioNotAvailable": "Radio ikke tilgjengelig for denne artisten",
          "songRemovedfromQueue": "Fjernet fra kø",
          "songRemovedfromQueueCurrSong":
              "Du kan ikke fjerne et spor som spilles",
          "songAddedToPlaylistAlert": "Spor lagt til i spillelisten",
          "songEnqueueAlert": "Spor lagt i spilleliste",
          "errorOccuredAlert": "En feil inntraff",
          "playlistCreatednsongAddedAlert":
              "Spilleliste opprettet og spor lagt til",
          "playlistRemovedAlert": "Spilleliste fjernet",
          "playlistBookmarkAddAlert": "Spilleliste bokmerket",
          "playlistBookmarkRemoveAlert": "Spillelistebokmerke fjernet",
          "albumBookmarkAddAlert": "Album bokmerket",
          "albumBookmarkRemoveAlert": "Albumsbokmerke fjernet",
          "artistBookmarkAddAlert": "Arist bokmerket",
          "artistBookmarkRemoveAlert": "Artistbokmerke fjernet",
          "dismiss": "Avslå",
          "lyricsNotAvailable": "Sangtekst utilgjengelig",
          "artistDesNotAvailable": "Beskrivelse utilgjengelig",
          "notaSongVideo": "Ikke et spor/musikkvideo",
          "operationFailed": "Operasjonen mislyktes",
          "CreateNewPlaylist": "Opprett ny spilleliste",
          "cancel": "Avbryt",
          "playlists": "Spillelister",
          "albums": "Album",
          "artists": "Artister",
          "settings": "Innstillinger",
          "favorites": "Favoritter",
          "recentlyPlayed": "Nylig spilt",
          "songs": "Spor",
          "libSongs": "Biblioteksspor",
          "libPlaylists": "Biblioteksspillelister",
          "libAlbums": "Biblioteksalbum",
          "libArtists": "Biblioteksartister",
          "items": "elementer",
          "retry": "Prøv igjen",
          "noOfflineSong": "Ingen frakoblede spor",
          "emptyPlaylist": "Tom spilleliste",
          "networkError1": "Nettverksfeil",
          "cachedOrOffline": "Hurtiglagret/frakoblet",
          "goToDownloadPage": "Klikk her for å gå til nedlastingssiden",
          "local": "Lokalt",
          "link": "Link",
          "unLink": "Koble fra",
          "linkPipedDes": "Link med piped for spillelister",
          "linkAlert": "Tilknyttet vellykket!",
          "unlinkAlert": "Koblet fra!",
          "playlistBlacklistAlert": "Spilleliste svartelistet!",
          "resetblacklistedplaylistDes":
              "Tilbakestill alle svartelistede spillelister",
          "stopMusicOnTaskClearDes":
              "Musikkavspilling stopper når appen sveipes bort fra oppgavebehandlingen",
          "selectAuthIns": "Velg Auth Instance",
          "stopMusicOnTaskClear": "Stopp musikk",
          "username": "Brukernavn",
          "reset": "Nullstille",
          "blacklistPlstResetAlert": "Tilbakestill vellykket!",
          "password": "Passord",
          "resetblacklistedplaylist": "Tilbakestill svartelistede spillelister"
        },
        "nl": {},
        "pl": {
          "home": "Główna",
          "songs": "Utwory",
          "playlists": "Playlisty",
          "albums": "Albumy",
          "artists": "Wykonawcy",
          "settings": "Ustawienia",
          "libAlbums": "Biblioteka Albumów",
          "libArtists": "Biblioteka Wykonawców",
          "items": "pozycje",
          "libSongs": "Biblioteka utworów",
          "libPlaylists": "Biblioteka Playlist",
          "networkError1": "Ups, błąd sieci!",
          "retry": "Spróbuj ponownie!",
          "noOfflineSong": "Brak utworów offline!",
          "recentlyPlayed": "Ostatnio odtwarzane",
          "favorites": "Ulubione",
          "emptyPlaylist": "Playlista jest pusta!",
          "enqueueAll": "Kolejkuj wszystkie",
          "renamePlaylist": "Zmień nazwę playlisty",
          "removePlaylist": "Usuń playlistę",
          "CreateNewPlaylist": "Utwórz nową playlistę",
          "create": "Utwórz",
          "createnAdd": "Utwórz i dodaj",
          "noBookmarks": "Brak zakładek!",
          "startRadio": "Uruchom radio",
          "playNext": "Odtwórz następny",
          "addToPlaylist": "Dodaj do playlisty",
          "noLibPlaylist": "Nie masz żadnej playlisty!",
          "enqueueSong": "Dodaj ten utwór do kolejki",
          "goToAlbum": "Przejdź do albumu",
          "viewArtist": "Zobacz wykonawcę",
          "shareSong": "Udostępnij ten utwór",
          "removeFromQueue": "Usuń z kolejki",
          "themeMode": "Motyw",
          "dynamic": "Dynamiczny",
          "systemDefault": "Domyślne ustawienia systemowe",
          "dark": "Ciemny",
          "light": "Jasny",
          "setDiscoverContent": "Wykryj zawartość",
          "quickPics": "Chwytliwe fotki",
          "discover": "Odkrywaj",
          "topMusicVid": "Najlepsze teledyski",
          "basedOnLast": "Na podstawie ostatniej interakcji",
          "trending": "Trendy",
          "cacheSongs": "Utwory w pamięci podręcznej",
          "skipSilence": "Pomiń ciszę",
          "cacheSongsDes":
              "Utwory w pamięci podręcznej podczas odtwarzania w przyszłości/odtwarzanie offline zajmie dodatkowe miejsce na urządzeniu",
          "skipSilenceDes": "Cisza będzie pomijana podczas odtwarzania muzyki",
          "streamingQuality": "Jakość streamingu",
          "streamingQualityDes": "Jakość strumienia muzyki",
          "high": "Wysoka",
          "low": "Niska",
          "equalizer": "Korektor dźwięku",
          "ignoreBatOpt": "Zignoruj optymalizację baterii",
          "equalizerDes": "Otwórz korektor systemowy",
          "ignoreBatOptDes":
              "Jeśli masz problemy z powiadomieniami lub odtwarzanie zostało zatrzymane przez optymalizację systemu, włącz tę opcję",
          "status": "Stan",
          "enabled": "Włączony",
          "disabled": "Wyłączony",
          "github": "Github",
          "githubDes":
              "Zobacz kod źródłowy na Github, \njeśli podoba Ci się ten projekt, nie zapomnij dać ⭐",
          "by": "autorstwa",
          "search": "Szukaj",
          "searchDes": "Utwory, Playlista, Album lub Wykonawca",
          "searchRes": "Wyniki wyszukiwania",
          "for1": "dla",
          "videos": "Teledyski",
          "viewAll": "Pokaż wszystko",
          "results": "Wyniki",
          "about": "O Harmony Music",
          "songRemovedfromQueue": "Usunięto z kolejki!",
          "radioNotAvailable": "Radio niedostępne dla tego wykonawcy!",
          "songRemovedfromQueueCurrSong":
              "Nie można usunąć aktualnie odtwarzanego utworu",
          "songAddedToPlaylistAlert": "Utwór dodano do playlisty!",
          "songAlreadyExists": "Ten utwór już istnieje!",
          "songEnqueueAlert": "Utwór dodano do kolejki!",
          "songRemovedAlert": "Usunięto z",
          "errorOccuredAlert": "Wystąpił błąd!",
          "playlistCreatedAlert": "Playlista została utworzona!",
          "playlistCreatednsongAddedAlert":
              "Utworzono playlistę i dodano utwór!",
          "playlistRenameAlert": "Zmiana nazwy zakończona powodzeniem!",
          "playlistRemovedAlert": "Usunięto Playlistę!",
          "playlistBookmarkAddAlert": "Dodano Playlistę do zakładek!",
          "playlistBookmarkRemoveAlert": "Usunięto Playlistę z zakładek!",
          "albumBookmarkAddAlert": "Dodano Album do zakładek!",
          "albumBookmarkRemoveAlert": "Usunięto Album z zakładek!",
          "artistBookmarkAddAlert": "Dodano Wykonawcę do zakładek!",
          "artistBookmarkRemoveAlert": "Usunięto Wykonawcę do zakładek!",
          "lyricsNotAvailable": "Tekst jest niedostępny!",
          "artistDesNotAvailable": "Opis jest niedostępny!",
          "newVersionAvailable": "Nowa wersja już dostępna!",
          "dontShowInfoAgain": "Nie pokazuj więcej tej informacji",
          "dismiss": "Odrzuć",
          "notaSongVideo": "To nie utwór muzyczny/teledysk!",
          "notaValidLink": "Nieprawidłowy link!",
          "operationFailed": "Operacja zakończyła się niepowodzeniem",
          "link": "Odnośnik",
          "unLink": "Odłącz",
          "local": "Lokalny",
          "selectAuthIns": "Wybierz instancję uwierzytelniania",
          "username": "Nazwa użytkownika",
          "password": "Hasło",
          "linkAlert": "Połączono pomyślnie!",
          "unlinkAlert": "Odłączono pomyślnie!",
          "reset": "Resetuj",
          "resetblacklistedplaylist": "Usuń playlistę z czarnej listy",
          "playlistBlacklistAlert": "Dodaj playlistę do czarnej listy!",
          "cachedOrOffline": "Pamięć podręczna/Oflline",
          "cancel": "Anuluj",
          "removeFromCache": "Usuń z pamięci podręcznej",
          "goToDownloadPage": "Kliknij tutaj, aby przejść do strony pobierania",
          "nomatch": "Nie znaleziono dopasowania dla",
          "linkPipedDes": "Link z potokiem dla list odtwarzania",
          "subscribers": "subskrybentów",
          "resetblacklistedplaylistDes":
              "Zresetuj wszystkie potokowane playlisty z czarnej listy",
          "blacklistPlstResetAlert": "Zresetowano pomyślnie!",
          "stopMusicOnTaskClearDes":
              "Odtwarzanie muzyki zostanie zatrzymane, gdy aplikacja zostanie usunięta z menedżera zadań",
          "stopMusicOnTaskClear": "Zatrzymaj muzykę"
        },
        "pt": {},
        "ro": {},
        "ru": {
          "home": "Начало",
          "songs": "Песни",
          "playlists": "Плейлисты",
          "albums": "Альбомы",
          "artists": "Артисты",
          "settings": "Настройки",
          "libSongs": "Библиотека Песни",
          "libPlaylists": "Библиотека Плейлисты",
          "libAlbums": "Библиотека Альбомы",
          "libArtists": "Библиотека Артисты",
          "items": "предметы",
          "networkError1": "Ой, ошибка сети!",
          "retry": "Повторите попытку!",
          "noOfflineSong": "Никаких оффлайн песен!",
          "recentlyPlayed": "Недавно играли",
          "favorites": "Любимые",
          "cachedOrOffline": "Кэш/офлайн",
          "emptyPlaylist": "Пустой плейлист!",
          "enqueueAll": "Добавить все в очередь",
          "renamePlaylist": "Rename Плейлист",
          "removePlaylist": "Удалить плейлист",
          "CreateNewPlaylist": "Создать новый плейлист",
          "cancel": "Отмена",
          "create": "Создать",
          "createnAdd": "Создать & добавить",
          "noBookmarks": "Без закладок!",
          "startRadio": "Начать радио",
          "playNext": "Играть дальше",
          "addToPlaylist": "Добавить в плейлист",
          "noLibPlaylist": "У вас нет lib playlist!",
          "enqueueSong": "Поставить эту песню в очередь",
          "goToAlbum": "Перейти в альбом",
          "viewArtist": "Посмотреть Артист",
          "shareSong": "Поделиться этой песней",
          "removeFromCache": "Удалить из кэша",
          "dynamic": "Динамический",
          "systemDefault": "Система по умолчанию",
          "dark": "темный",
          "light": "свет",
          "quickPics": "Быстрый выбор",
          "discover": "Обнаружить",
          "trending": "В тренде",
          "topMusicVid": "Лучшие музыкальные клипы",
          "basedOnLast": "На основе последнего взаимодействия",
          "cacheSongs": "Cache песни",
          "cacheSongsDes":
              "Кэширование песен во время игры на будущее / оффлайн воспроизведение, это займет дополнительное пространство на вашем устройстве",
          "skipSilence": "Пропустить тишину",
          "skipSilenceDes":
              "Тишина будет пропущена в музыкальном воспроизведении",
          "streamingQuality": "Потоковое качество",
          "streamingQualityDes": "Качество музыкального потока",
          "high": "Высокая",
          "low": "Низкий",
          "equalizer": "Равномер",
          "equalizerDes": "открытый системный эквалайзер",
          "ignoreBatOpt": "Игнорировать оптимизацию батареи",
          "ignoreBatOptDes":
              "Если вы столкнулись с проблемами уведомлений или воспроизведение остановлено оптимизацией системы, пожалуйста, включите этот вариант",
          "status": "Статус",
          "enabled": "Включить",
          "disabled": "Отключить",
          "github": "Гитуб",
          "githubDes":
              "Посмотреть исходный код GitHub\nесли вам нравится этот проект, не забудьте дать ⭐",
          "by": "по",
          "search": "Поиск",
          "searchDes": "Песни,Playlist,Album или артист",
          "searchRes": "Результаты поиска",
          "for1": "для",
          "videos": "Видео",
          "viewAll": "Посмотреть все",
          "results": "Результаты",
          "nomatch": "Матч не найден",
          "subscribers": "подписчики",
          "about": "О",
          "radioNotAvailable": "Радио не доступно для этого художника!",
          "songRemovedfromQueue": "Удалено из очереди!",
          "songRemovedfromQueueCurrSong":
              "Вы не можете удалить в настоящее время играя песню",
          "songAddedToPlaylistAlert": "Песня добавлена в плейлист!",
          "songAlreadyExists": "Песня уже существует!",
          "songEnqueueAlert": "Песня поставлена в очередь!",
          "errorOccuredAlert": "Произошла ошибка!",
          "playlistCreatedAlert": "Playlist создан!",
          "playlistCreatednsongAddedAlert":
              "Playlist создан и добавлена песня!",
          "playlistRenameAlert": "Переименованные успешно!",
          "playlistRemovedAlert": "Плейлист удален!",
          "playlistBookmarkAddAlert": "Плейлист добавлен в закладки!",
          "playlistBookmarkRemoveAlert": "Playlist bookmark удален!",
          "albumBookmarkAddAlert": "Альбом в закладках!",
          "artistDesNotAvailable": "Описание не доступно!",
          "newVersionAvailable": "Новая версия доступна!",
          "dontShowInfoAgain": "Не показывать эту информацию снова",
          "dismiss": "Увольнять",
          "notaSongVideo": "Не песня/Музыка-Видео!",
          "albumBookmarkRemoveAlert": "Закладка альбома удалена!",
          "artistBookmarkAddAlert": "Художник в закладках!",
          "artistBookmarkRemoveAlert": "Авторская закладка удалена!",
          "notaValidLink": "Не корректная ссылка!",
          "operationFailed": "Операция не удалось",
          "removeFromQueue": "Удалить из очереди",
          "themeMode": "Тематический режим",
          "setDiscoverContent": "Установить открыть контент",
          "songRemovedAlert": "Удалено из",
          "lyricsNotAvailable": "Тексты не доступны!",
          "linkPipedDes": "Ссылка на Piped для плейлистов",
          "linkAlert": "Связано успешно!",
          "unlinkAlert": "Связь успешно отключена!",
          "reset": "вправлять",
          "resetblacklistedplaylistDes":
              "Сбросить все плейлисты из черного списка из Piped",
          "goToDownloadPage":
              "Нажмите здесь, чтобы перейти на страницу загрузки",
          "local": "Местный",
          "link": "Связь",
          "unLink": "Отключить",
          "selectAuthIns": "Выберите экземпляр аутентификации",
          "username": "Имя пользователя",
          "password": "Пароль",
          "playlistBlacklistAlert": "Плейлист занесен в черный список!",
          "blacklistPlstResetAlert": "Сброс выполнен успешно!",
          "resetblacklistedplaylist": "Сбросить плейлисты из черного списка",
          "stopMusicOnTaskClear": "Остановить музыку",
          "stopMusicOnTaskClearDes":
              "Воспроизведение музыки остановится, когда приложение будет удалено из диспетчера задач.",
          "communityplaylists": "Плейлисты сообщества",
          "languageDes": "Язык приложения",
          "customInsSelectMsg": "Пожалуйста, выберите пользовательский вход",
          "allFieldsReqMsg": "Все поля обязательны",
          "rename": "Переименовать",
          "selectAuthInsMsg": "Пожалуйста, выберите экземпляр Authentication!",
          "customIns": "Свои серверы",
          "Piped": "Piped",
          "topmusicvideos": "Лучшие музыкальные клипы",
          "singles": "Синглы",
          "language": "Язык",
          "hintApiUrl": "URL-адрес API экземпляра Piped",
          "removeFromPlaylist": "Удалить из плейлиста",
          "featuredplaylists": "Избранные плейлисты",
          "quickpicks": "Быстрый выбор"
        },
        "sk": {},
        "sr": {},
        "ta": {},
        "te": {},
        "tr": {
          "renamePlaylist": "Çalma Listesini Yeniden Adlandır",
          "networkError1": "Oops ağ hatası!",
          "libSongs": "Kütüphane Şarkıları",
          "communityplaylists": "Topluluk çalma listeleri",
          "libAlbums": "Kütüphane Albümleri",
          "enqueueAll": "Tümünü kuyruğa al",
          "create": "Yaratmak",
          "noBookmarks": "Yer işaretleri yok!",
          "playlists": "Çalma Listeleri",
          "rename": "Yeniden adlandır",
          "items": "öğeler",
          "startRadio": "Radyo başlat",
          "libArtists": "Kütüphane Sanatçıları",
          "removePlaylist": "Çalma listesini kaldır",
          "addToPlaylist": "Çalma listesine ekle",
          "cachedOrOffline": "Önbelleğe Alınmış/Çevrimdışı",
          "retry": "Tekrar dene",
          "artists": "Sanatçılar",
          "albums": "Albümler",
          "recentlyPlayed": "Son çalınan",
          "createnAdd": "Oluştur ve ekle",
          "singles": "Single'lar",
          "emptyPlaylist": "Çalma Listesini Boşalt!",
          "favorites": "Favoriler",
          "home": "Anasayfa",
          "cancel": "İptal et",
          "libPlaylists": "Kütüphane Playlists",
          "CreateNewPlaylist": "Çalma listesi oluştur",
          "playNext": "Bir sonra çal",
          "songs": "Şarkılar",
          "settings": "Ayarlar",
          "noOfflineSong": "Çevrimdışı şarkı yok!",
          "featuredplaylists": "Öne çıkan listeler"
        },
        "uk": {},
        "ur": {},
        "vi": {},
        "zh_Hans": {
          "home": "主页",
          "songs": "歌曲",
          "playlists": "播放列表",
          "albums": "专辑",
          "artists": "艺术家",
          "settings": "设置",
          "libSongs": "歌曲库",
          "libPlaylists": "播放列表库",
          "libAlbums": "专辑库",
          "libArtists": "图书馆",
          "items": "项目",
          "networkError1": "网络错误!",
          "retry": "页: 1!",
          "recentlyPlayed": "最近",
          "favorites": "陪审团",
          "cachedOrOffline": "Cached/Oflline",
          "enqueueAll": "开 幕",
          "renamePlaylist": "名单",
          "removePlaylist": "F. 移居名单",
          "create": "创建",
          "createnAdd": "创建和增加",
          "noBookmarks": "没有书记!",
          "startRadio": "导 言",
          "playNext": "下表",
          "addToPlaylist": "增加名单",
          "noLibPlaylist": "你的don't有任何利b的名单!",
          "enqueueSong": "诗歌",
          "goToAlbum": "B. 集成",
          "viewArtist": "View Arist",
          "shareSong": "分享这一歌曲",
          "removeFromQueue": "D. 取消询问权",
          "removeFromCache": "D. 从因果关系搬出",
          "themeMode": "主题",
          "dynamic": "动态",
          "systemDefault": "系统违约",
          "dark": "黑暗",
          "light": "评 注",
          "setDiscoverContent": "确定内容",
          "quickPics": "快速培训",
          "discover": "排 物",
          "trending": "通 约",
          "topMusicVid": "Top Music Videos",
          "basedOnLast": "基于最后的互动",
          "cacheSongs": "Cach Songs",
          "cacheSongsDes": "每个歌歌唱在未来/投机时,将给你的装置增加空间。",
          "skipSilence": "Skip沉默",
          "skipSilenceDes": "音乐会的沉默会",
          "streamingQuality": "提高质量",
          "streamingQualityDes": "音乐流的质量",
          "high": "高级专员",
          "low": "低 度",
          "equalizer": "平等",
          "equalizerDes": "开放制度",
          "ignoreBatOpt": "Ignore电池优化",
          "ignoreBatOptDes": "如果你面临通知问题或系统最优化的阻碍,请使这一选择能够实现。",
          "status": "现状",
          "enabled": "附录",
          "disabled": "残疾人",
          "github": "吉 布",
          "githubDes": "View GitHub源代码\n如你同该项目一样,捐助者打算提供一份《公约》的批准。",
          "by": "评 注",
          "search": "建 议",
          "searchDes": "Songs,Playlist,Album或Arist",
          "searchRes": "搜索结果",
          "for1": "附 件",
          "videos": "录像",
          "viewAll": "无",
          "results": "成果",
          "nomatch": "未发现任何库存",
          "subscribers": "用户",
          "about": "约 门",
          "radioNotAvailable": "无这种艺术家的电台!",
          "songRemovedfromQueue": "弃权!",
          "songRemovedfromQueueCurrSong": "你可以拆除目前玩耍的诗歌",
          "songAddedToPlaylistAlert": "中文又增加了一分钟。!",
          "songAlreadyExists": "已经存在!",
          "songEnqueueAlert": "日子!",
          "songRemovedAlert": "撤职",
          "errorOccuredAlert": "出现一些错误!",
          "playlistCreatedAlert": "候选人创建了!",
          "playlistCreatednsongAddedAlert": "发言人创建了和歌曲!",
          "playlistRenameAlert": "成功!",
          "playlistRemovedAlert": "名单中除名!",
          "playlistBookmarkAddAlert": "Playlist书记!",
          "playlistBookmarkRemoveAlert": "候选人书记!",
          "albumBookmarkAddAlert": "Album书记!",
          "albumBookmarkRemoveAlert": "Album的书记!",
          "artistBookmarkAddAlert": "书记!",
          "artistBookmarkRemoveAlert": "书记!",
          "lyricsNotAvailable": "无法提供!",
          "artistDesNotAvailable": "说明!",
          "newVersionAvailable": "新版本!",
          "dontShowInfoAgain": "捐血再次表明这一点",
          "dismiss": "缺点",
          "notaSongVideo": "不是Song/Music-Video!",
          "notaValidLink": "没有有效联系!",
          "operationFailed": "行动失败",
          "noOfflineSong": "无线歌!",
          "emptyPlaylist": "胜利!",
          "CreateNewPlaylist": "创设新的名录",
          "cancel": "增 编"
        },
      };
}
